### ISSUE TITLE
Documentation problems

### ISSUE THREAD

**Issue by LWJerri** [Riddea/Riddea#75]
**/v1​/users​/{userId}​/collections**
Missed field `id` in collection.

**/v1/collections/{id}/images**
Return other JSON object:
```json
{
"nextPage": true,
"data": [
  "datafile1"
]
}
```

**/v1/collections/{id}**
Missed field `id` in collection.

**Comment by Satont** [comment]
[ ] - `/v1/collections/{id}/images` missed query params

**Comment by LWJerri** [comment]
> * [ ]  - `/v1/collections/{id}/images` missed query params

Oh, yes, I missed saying about this problem.
